export type Question = {
  id: number
  question: string
  options: string[]
  correctIndex: number
  difficulty: "easy" | "medium" | "hard"
}

export const questions: Question[] = [
  {
    id: 1,
    question: "The 14th letter of the alphabet is:",
    options: ["D", "N", "S", "V"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: 2,
    question: "How many of the following pairs are EXACT duplicates? 219637-291637, 55443-5543, 67891-67819, 25554-25554, 97998-97998, 6629-6692",
    options: ["5", "2", "1", "4"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: 3,
    question: "Are the following two words similar, contradictory, or unrelated? Arduous / Grueling",
    options: ["Similar", "Contradictory", "Unrelated"],
    correctIndex: 0,
    difficulty: "easy",
  },

  {
    id: 4,
    question: "0.3458 / 1 = ?",
    options: ["3.458", "30.58", "0.8764", "0.3458", "0.03458"],
    correctIndex: 3,
    difficulty: "easy",
  },
  {
  id: 5,
  question: "72.4% equals:",
  options: ["0.00724", "7.24", "0.0724", "72.4", "0.724"],
  correctIndex: 4,
  difficulty: "easy",
},
{
  id: 6,
  question: "Arrange the following words to form a complete sentence: seven there are in a days week. Is that sentence true or false?",
  options: ["True", "False", "Neither true nor false"],
  correctIndex: 0,
  difficulty: "easy",
},
{
  id: 7,
  question: "Giraffe is to animal as _ _ _ is to color",
  options: ["Sight", "Red", "Favorite", "Warmth"],
  correctIndex: 1,
  difficulty: "easy",
},
{
  id: 8,
  question: "October is to November as _ _ _ is to April",
  options: ["January", "December", "March", "August"],
  correctIndex: 2,
  difficulty: "easy",
},
{
  id: 9,
  question: "-73 + -59 equals:",
  options: ["-137", "-132", "14", "-14", "-106"],
  correctIndex: 1,
  difficulty: "easy",
},
{
  id: 10,
  question: "Three motorcycles collectively have _ _ _ wheels",
  options: ["Two", "Three", "Four", "Six"],
  correctIndex: 3,
  difficulty: "easy",
},
{
  id: 11,
  question: "A car travels 20 feet in 0.5 seconds. At that speed, how far will the car travel in one minute?",
  options: ["2500 feet", "2000 feet", "3400 feet", "2400 feet"],
  correctIndex: 3,
  difficulty: "medium",
},
{
  id: 12,
  question: "Which word does not belong?",
  options: ["Poem", "Drawing", "Boulder", "Painting", "Sculpture"],
  correctIndex: 2,
  difficulty: "medium",
},
{
  id: 13,
  question: "What is 2100 hours in standard time?",
  options: ["3:00 pm", "11:00 pm", "9:00 pm", "5:00 pm"],
  correctIndex: 2,
  difficulty: "medium",
},
{
  id: 14,
  question: "John has a 0.5 dozen blue marbles, 2.5 dozen green marbles, and 2 dozen red marbles. How many marbles does John have in total?",
  options: ["60", "108", "48", "74"],
  correctIndex: 0,
  difficulty: "medium",
},
{
  id: 15,
  question: "A bus driver picked up 8 passengers in the morning, 19 in the afternoon, and 13 in the evening. How many passengers did he pick up in total?",
  options: ["38", "39", "40", "41"],
  correctIndex: 2,
  difficulty: "medium",
},
{
  id: 16,
  question: "Are the following two words similar, contradictory, or unrelated? Qualify / Quantify",
  options: ["Similar", "Contradictory", "Unrelated"],
  correctIndex: 2,
  difficulty: "medium",
},
{
  id: 17,
  question: "How many inches are in 14.5 feet?",
  options: ["174", "204", "190", "148"],
  correctIndex: 0,
  difficulty: "medium",
},
{
  id: 18,
  question: "How many of the six pairs from the list below are EXACT duplicates?  2887-2887, 1890-1891, 2437-2437, 8612-8612, 3842-3482, 5276-5270",
  options: ["5", "2", "1", "3"],
  correctIndex: 3,
  difficulty: "medium",
},
{
  id: 19,
  question: "Are the following two words similar, contradictory, or unrelated? Withhold / Provide",
  options: ["Similar", "Contradictory", "Unrelated"],
  correctIndex: 1,
  difficulty: "medium",
},
{
  id: 20,
  question: "A family is traveling to a location 150 miles away. At what constant speed should they travel to get there in 2.5 hours?",
  options: ["60 mph", "65 mph", "70 mph", "75 mph"],
  correctIndex: 0,
  difficulty: "medium",
},
{
  id: 21,
  question: "Your bill is $18.52 and you pay $35. How much change should you get?",
  options: ["$20.42", "$16.48", "$22.08", "$14.89"],
  correctIndex: 1,
  difficulty: "medium",
},
{
  id: 22,
  question: "(20 / 4) * (15 / 3) =",
  options: ["20", "5", "25", "5.5", "12"],
  correctIndex: 2,
  difficulty: "medium",
},
{
  id: 23,
  question: "How many seconds are in 8.5 minutes?",
  options: ["445", "510", "525", "390"],
  correctIndex: 1,
  difficulty: "medium",
},
{
  id: 24,
  question: "A store has discounted a sweater by 20%. If the current price of the sweater is $20, what was the original sales price?",
  options: ["$25", "$22", "$27", "$24"],
  correctIndex: 0,
  difficulty: "medium",
},
{
  id: 25,
  question: "A plumber makes $17.50 per hour plus $3 for every service call he completes. Last week he worked 32 hours and completed 7 service calls. How much money did he make?",
  options: ["$623", "$495", "$512", "$581"],
  correctIndex: 3,
  difficulty: "hard",
},
{
  id: 26,
  question: "There are 6 times as many 5th graders as there are 4th graders at a particular school. If the combined total is 140 students, how many 4th graders are there?",
  options: ["30", "17", "20", "26"],
  correctIndex: 2,
  difficulty: "hard",
},
{
  id: 27,
  question: "Joshua earns $15 per hour mowing lawns and $5.50 for every tree he trims. Yesterday he mowed lawns for 5 hours and trimmed 3 trees. How much money did he make?",
  options: ["$96.50", "$100.50", "$87.00", "$91.50"],
  correctIndex: 3,
  difficulty: "hard",
},
{
  id: 28,
  question: "If lemons cost $1 and watermelons cost $1.60, how many of each were sold for a total of $8.80?",
  options: [
    "3 lemons and 3 watermelons",
    "6 watermelons",
    "3 lemons and 2 watermelons",
    "4 lemons and 3 watermelons",
  ],
  correctIndex: 3,
  difficulty: "hard",
},
{
  id: 29,
  question: "At a school, there are twice as many girl soccer players as boy soccer players. If the total number of soccer players is 96, how many girl soccer players are there?",
  options: ["64", "24", "32", "48"],
  correctIndex: 0,
  difficulty: "hard",
},
{
  id: 30,
  question: "If pumpkin pies cost $2 and apple pies cost $2.45, how many of each were sold for a total of $11.35?",
  options: [
    "1 pumpkin pie and 5 apple pies",
    "2 pumpkin pies and 3 apple pies",
    "3 pumpkin pies and 4 apple pies",
    "5 apple pies",
  ],
  correctIndex: 1,
  difficulty: "hard",
},
]